### PR TITLE
Update gem spec. Update outdated gems. Remove Ruby 1.x support. Ruby 3.x webrick support

### LINKED ISSUE #22: Faraday version mismatch with ably-ruby
Hi,
`ably-ruby` has been [recently updated](https://github.com/ably/ably-ruby/commit/9d7562872cfb869cf8e2b42182384bd21ec45d14) to support faraday 2.2.
However, since `ably-ruby` is not a dependency of `ably-ruby-rest`, but rather just a git submodule, the `faraday` version locked in `ably-ruby-rest` is still version 1. 
This makes it impossible to work with the latest version of `ably-ruby-rest`.

Thanks!

### PR DESCRIPTION
**Pull request by lukaszsliwa**
- [x] Update able-rest.gemspec.
- [x] Remove Ruby 1.x support.
- [x] Add Ruby 3.x and webrick support.
- [x] Update outdated gems.
- [x] Add faraday 2.2 and typhoeus integration.

Resolves #22

### CODE REVIEW

**Review by AndyNicks — APPROVED** [review]

**Review by owenpearson — APPROVED** [review]
LGTM 👍

**Comment by thatguysimon** [comment]
Thanks for the quick fix guys!
When can we expect a new version to be published?
@lukaszsliwa @AndyNicks @owenpearson

**Comment by owenpearson** [comment]
@thatguysimon Just about to start the release process now 🙂

**Comment by owenpearson** [comment]
@thatguysimon all done now: https://github.com/ably/ably-ruby-rest/releases/tag/v1.2.2. Let us know if you have any further issues

**Comment by thatguysimon** [comment]
Thanks @owenpearson! Looks good on our side.

**Pull request merged**
